using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projem
{
    public partial class FrmUretilecekIsEmirleri : Form
    {
        SqlConnection conn = new SqlConnection("Data Source=HALIL;Initial Catalog=ERP;Integrated Security=True");
        public FrmUretilecekIsEmirleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
        }

        private void FrmUretilecekIsEmirleri_Load(object sender, EventArgs e)
        {
            //gridView1.OptionsBehavior.Editable = false;
        }
        void isemrilisteleme()
        {
            conn.Open();
            DataTable dt = new DataTable();
            SqlCommand cmd = new SqlCommand("select ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,ISEMRI_ACIKLAMASI,SUBSTRING(ISEMRI_TARIHI,0,10) AS 'İŞ EMRİ TARİHİ', SUBSTRING(TESLIM_TARIHI,0,10) AS 'TESLİM TARİHİ',SIPARIS_NO,MIKTAR,SIPKALEM_ID FROM TBL_ISEMRI WHERE DURUM = 'Y' ", conn);
            SqlDataAdapter dataAdapter = new SqlDataAdapter(cmd);
            dataAdapter.Fill(dt);
            gridControl1.DataSource = dt;
            conn.Close();
        }
        string x1="";
        void uretimsonukaydinumarasihesaplama()
        {
            conn.Open();
            SqlCommand sorgu1 = new SqlCommand("SELECT TOP 1 CONCAT('U',REPLICATE('0',10-(LEN(SUBSTRING(URETIMSONUKAYDI_NUMARASI,2,9)+1)+1)),SUBSTRING(URETIMSONUKAYDI_NUMARASI,2,9)+1) FROM TBL_URETIMSONUKAYITLARI ORDER BY URETIMSONUKAYDI_NUMARASI DESC", conn);
            SqlDataReader dr1 = sorgu1.ExecuteReader();
            while (dr1.Read())
            {
                x1= dr1[0].ToString();
            }
            conn.Close();
        }

        String sipno = "";
        string isemrino = "";
        private void repositoryItemButtonEdit1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            int x = gridView1.FocusedRowHandle;
            isemrino = gridView1.GetRowCellValue(x,"ISEMRI_NUMARASI").ToString();
            sipno = gridView1.GetRowCellValue(x, "SIPARIS_NO").ToString();
            DialogResult secenek = MessageBox.Show("Seçili Ürünü Üretmek İstediğinizden Emin misiniz?", "Üretim Sonu Kaydı Uyarısı",MessageBoxButtons.YesNo,MessageBoxIcon.Information);
            if(secenek == DialogResult.Yes)
            {
                string stokkodu = "";
                string stokadi = "";
                string miktar = "";
                string sipkalemID = "";
                string musterikodu = "";
                string musteradi = "";

                conn.Open();    
                SqlCommand sorgu1 = new SqlCommand("select * from TBL_ISEMRI where ISEMRI_NUMARASI = '"+isemrino+"'",conn);
                SqlDataReader dr1 = sorgu1.ExecuteReader();
                while (dr1.Read())
                {
                    stokkodu = dr1[1].ToString();
                    stokadi = dr1[2].ToString();
                    miktar = dr1[7].ToString();
                    sipkalemID = dr1[8].ToString();
                }
                conn.Close();

                conn.Open();
                SqlCommand sorgu2 = new SqlCommand("SELECT SIP.MUSTERI_KODU, MK.MUSTERI_ADI FROM TBL_SIPARISLER SIP LEFT JOIN TBL_MUSTERIKAYITLARI MK ON SIP.MUSTERI_KODU = MK.MUSTERI_KODU WHERE SIPARIS_NO = '"+sipno+"'", conn);
                SqlDataReader dr2 = sorgu2.ExecuteReader();
                while (dr2.Read())
                {
                    musterikodu = dr2[0].ToString();
                    musteradi = dr2[1].ToString();
                }
                conn.Close();

                uretimsonukaydinumarasihesaplama();
                conn.Open();
                SqlCommand sorgu3 = new SqlCommand("INSERT INTO TBL_URETIMSONUKAYITLARI (URETIMSONUKAYDI_NUMARASI,ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,MIKTAR,SIPARIS_NUMARASI,SIPKALEM_ID,MUSTERI_KODU,MUSTERI_ADI) VALUES ('" + x1 + "','" + isemrino + "','" + stokkodu + "','" + stokadi + "','" + miktar.Replace(',', '.') + "','" + sipno + "','" + sipkalemID + "','" + musterikodu + "','" + musteradi + "')", conn);
                sorgu3.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu4 = new SqlCommand("UPDATE TBL_ISEMRI SET DURUM = 'E' WHERE ISEMRI_NUMARASI = '" + isemrino + "'", conn);
                sorgu4.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu5 = new SqlCommand("UPDATE TBL_SIPARISKALEMLERI SET URETIMDURUMU = 'B' WHERE SIPKALEM_ID = '" + sipkalemID + "'", conn);
                sorgu5.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu6 = new SqlCommand("INSERT INTO TBL_STOK_HAREKETLERI (URETIMSONUKAYDI_NUMARASI,ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,G_MIKTAR,C_MIKTAR,MUSTERI_ADI,ACIKLAMA) VALUES ('" + x1 + "','" + isemrino + "','" + stokkodu + "','" + stokadi + "','" + miktar.Replace(',', '.') + "','0','" + musteradi + "','ÜRETİM')", conn);
                sorgu6.ExecuteNonQuery();
                conn.Close();

                isemrilisteleme();
                MessageBox.Show("Üretim İşlemi Başarı İle Gerçekleştirilimiştir.");
            }
            else
            {
                MessageBox.Show("Üretim İşlemi İptal Edilmiştir!!");
            }
            
        }
    }
}
